### ISSUE TITLE
unable to run your role

### ISSUE THREAD

**Issue by drmax24** [bbatsche/Ansible-PHP-Site-Role#1]
I have an error on Ubuntu 16.04

fatal: [5.79.106.151]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0755", "msg": "chgrp failed: failed to look up group web-admin", "owner": "root", "path": "/etc/nginx/sites-available", "size": 4096, "state": "directory", "uid": 0}

**Comment by bbatsche** [comment]
Hi @MCON,

It looks like you may have two issues here. First and foremost, my role is not currently validated against Ubuntu 16.04. I would very much like to target the current LTS releases of Ubuntu but at the moment the only version I've been able to confirm as working is Trusty or 14.04. (This is going to prove especially difficult for this role in particular, as Ubuntu now supports two distinctly different versions of PHP).

Secondly, the actual error indicates you do not have a `web-admin` group on your server. My site building roles require the current user (ie, your user account) to belong to this group in order to give a good balance of security and flexibility. As noted in the [README](https://github.com/bbatsche/Ansible-PHP-Site-Role#requirements) you can either create that user manually or use my existing [bbatsche.Base](/bbatsche/Ansible-Common-Role) to create it for you.

Thanks for reaching out and using my Ansible roles!
